HAI 1.3

HOW IZ I factorial YR n
	I HAS A prod ITZ 1
	IM IN YR LOOP UPPIN YR i TIL BOTH SAEM i AN n
		prod R PRODUKT OF prod AN SUM OF i AN 1
	IM OUTTA YR LOOP
	FOUND YR prod
IF U SAY SO

I HAS A n
GIMMEH n
n IS NOW A NUMBR
VISIBLE I IZ factorial YR n MKAY

KTHXBYE
